import logging
import uuid
import time
import hashlib
from typing import Dict, Any, Tuple, List
import cv2
import numpy as np

from app.core.pipeline.quality_check import ImageQualityAnalyzer, QualityReport
from app.core.pipeline.classification import DocumentClassifier
from app.core.model_manager import model_manager
from app.models.schema import UniversalKnowledgeSchema, KnowledgeObject, ProcessingMetadata, RelationshipEdge, CommonDocumentObject
from app.core.chunking import SemanticChunker
from app.core.vision.pipeline import VisionPipeline
from app.core.events import event_bus
from app.core.cache.fingerprint import DocumentFingerprinter

logger = logging.getLogger(__name__)

class PipelineOrchestrator:
    """
    End-to-End Orchestrator for the Processing Pipeline.
    Manages Fingerprinting, Quality Check, Classification, Routing, Schema Generation, and Chunking.
    Receives a CommonDocumentObject from the IngestionEngine.
    """

    @staticmethod
    def process_document(cdo: CommonDocumentObject) -> Tuple[UniversalKnowledgeSchema, List[Dict[str, Any]]]:
        document_id = cdo.document_id
        
        # 1. Pipeline Start
        event_bus.emit("PipelineStarted", {"document_id": document_id, "filename": cdo.filename})
        
        # 2. Level 1 Cache Check
        # The fingerprint was generated by the adapter
        sha256_hash = cdo.fingerprint
        is_duplicate, cached_schema = DocumentFingerprinter.check_duplicate(sha256_hash)
        if is_duplicate and cached_schema:
            chunks = SemanticChunker.chunk_schema(cached_schema)
            event_bus.emit("PipelineCompleted", {"document_id": cached_schema.document_id, "status": "CacheHit"})
            return cached_schema, chunks

        # Phase 1: We assume single image array for now (ImageAdapter).
        # Phase 2: Iterate over cdo.pages / cdo.images / cdo.text_blocks
        
        # Fallback empty logic if no images
        final_text = ""
        overall_confidence = 0.0
        ocr_engine_id = "none"
        quality_metrics = {}
        classification = {"final_category": "unknown", "routing_decision": "none"}
        enhancement_trace = []
        profile_used = cdo.processing_profile
        
        # Collect blocks and relationships
        blocks = []
        relationships = []
        
        # Resolve images from in-memory list or extracted disk assets
        images_to_process = list(cdo.images) if cdo.images else []
        if not images_to_process and cdo.extracted_assets:
            for asset_p in cdo.extracted_assets:
                loaded = cv2.imread(str(asset_p))
                if loaded is not None:
                    images_to_process.append(loaded)
                    
        if getattr(cdo, "modality", "").lower() in ["audio", "video"]:
            # Native Audio / Video Modality logic: Each segment is an audio_segment/video_segment knowledge object
            overall_confidence = 0.95
            for page in cdo.pages:
                page_num = page.get("page_num", 1) if isinstance(page, dict) else 1
                meta = page.get("metadata", {}) if isinstance(page, dict) else {}
                t_str = meta.get("timestamp_str", "00:00 - 00:00")
                
                # Create a Page Object for graph representation
                page_ko_id = str(uuid.uuid4())
                blocks.append(KnowledgeObject(
                    knowledge_object_id=page_ko_id,
                    parent_document_id=document_id,
                    block_type="page",
                    content=f"Video Segment {page_num} of {cdo.filename}",
                    engine_used="video_intelligence" if cdo.modality == "video" else "whisper_audio",
                    confidence=1.0,
                    page_number=page_num,
                    metadata=meta
                ))
                
                # Check for structured audio_segment or video_segment elements
                segment_elements = [el for el in page.get("elements", []) if el.get("type") in ["audio_segment", "video_segment"]]
                if segment_elements:
                    for el in segment_elements:
                        ko_id = el.get("id") or str(uuid.uuid4())
                        el_type = el.get("type", "video_segment")
                        blocks.append(KnowledgeObject(
                            knowledge_object_id=ko_id,
                            parent_document_id=document_id,
                            parent_object_id=page_ko_id,
                            page_number=page_num,
                            block_type=el_type,
                            content=el.get("text", ""),
                            engine_used="video_intelligence" if cdo.modality == "video" else "whisper_audio",
                            confidence=el.get("confidence", 0.95),
                            metadata={
                                "start_time": el.get("start_time", 0.0),
                                "end_time": el.get("end_time", 0.0),
                                "timestamp_str": el.get("timestamp_str", t_str),
                                "modality": cdo.modality
                            }
                        ))
                        relationships.append(RelationshipEdge(
                            source_id=ko_id,
                            target_id=page_ko_id,
                            relationship_type="CHILD_OF"
                        ))
                else:
                    for text_block in page.get("text_blocks", []):
                        ko_id = str(uuid.uuid4())
                        b_type = "video_segment" if cdo.modality == "video" else "audio_segment"
                        blocks.append(KnowledgeObject(
                            knowledge_object_id=ko_id,
                            parent_document_id=document_id,
                            parent_object_id=page_ko_id,
                            page_number=page_num,
                            block_type=b_type,
                            content=text_block,
                            engine_used="video_intelligence" if cdo.modality == "video" else "whisper_audio",
                            confidence=0.95,
                            metadata={
                                "start_time": meta.get("start_time", 0.0),
                                "end_time": meta.get("end_time", 0.0),
                                "timestamp_str": t_str,
                                "modality": cdo.modality
                            }
                        ))
                        relationships.append(RelationshipEdge(
                            source_id=ko_id,
                            target_id=page_ko_id,
                            relationship_type="CHILD_OF"
                        ))
            quality_metrics = {"category": cdo.modality}

        elif (cdo.modality == "image" or not cdo.pages) and images_to_process:
            # Phase 2 Vision Intelligence Layer for image adapter / visual assets
            image = images_to_process[0]
            
            quality_report = ImageQualityAnalyzer.analyze(image)
            event_bus.emit("QualityReportGenerated", {"document_id": document_id, "iqs": quality_report.quality_score})
            profile_used = quality_report.profile_used
            
            classification = DocumentClassifier.classify(quality_report)
            routing_decision = classification["routing_decision"]
            event_bus.emit("ClassificationCompleted", {"document_id": document_id, "routing": routing_decision})
            
            # Preprocessing
            processed_image = image.copy()
            enhancement_trace = ["Original"]
            for op in quality_report.recommended_pipeline:
                enhancement_trace.append(op)
                
            # Create a Page Object
            page_ko_id = str(uuid.uuid4())
            blocks.append(KnowledgeObject(
                knowledge_object_id=page_ko_id,
                parent_document_id=document_id,
                block_type="page",
                content=f"Page 1 of {cdo.filename}",
                engine_used="native",
                confidence=1.0,
                page_number=1
            ))
            
            # STAGE 1: PRIMARY OCR TEXT EXTRACTION
            # Run Tesseract (fast and highly accurate on diagrams/scans) with PaddleOCR fallback
            ocr_model = model_manager.get_model("ocr", "tesseract") or model_manager.get_model("ocr", "paddleocr")
            
            final_text = ""
            overall_confidence = 0.0
            
            if ocr_model:
                try:
                    ocr_result = ocr_model.predict(processed_image)
                    event_bus.emit("OCRCompleted", {"document_id": document_id, "engine": "ocr"})
                    final_text = ocr_result.get("text", "").strip()
                    overall_confidence = ocr_result.get("confidence", 0.0)
                except Exception as oe:
                    logger.warning(f"Primary OCR failed on {cdo.filename}: {oe}")
                    
            if not final_text:
                # Try fallback OCR engine
                fallback_model = model_manager.get_model("ocr", "paddleocr")
                if fallback_model and fallback_model != ocr_model:
                    try:
                        f_res = fallback_model.predict(processed_image)
                        final_text = f_res.get("text", "").strip()
                        overall_confidence = f_res.get("confidence", 0.0)
                    except Exception as fe:
                        logger.warning(f"Fallback OCR failed on {cdo.filename}: {fe}")
            
            if final_text:
                ocr_paragraphs = [p.strip() for p in final_text.split("\n\n") if p.strip()]
                if not ocr_paragraphs:
                    ocr_paragraphs = [final_text]
                for p_text in ocr_paragraphs:
                    ocr_ko_id = str(uuid.uuid4())
                    blocks.append(KnowledgeObject(
                        knowledge_object_id=ocr_ko_id,
                        parent_document_id=document_id,
                        parent_object_id=page_ko_id,
                        page_number=1,
                        block_type="paragraph",
                        content=p_text,
                        engine_used="ocr",
                        confidence=overall_confidence if overall_confidence > 0 else 0.95
                    ))
                    relationships.append(RelationshipEdge(
                        source_id=ocr_ko_id,
                        target_id=page_ko_id,
                        relationship_type="CHILD_OF"
                    ))
                logger.info(f"Image {cdo.filename} OCR extracted {len(final_text)} characters in {len(ocr_paragraphs)} paragraphs.")
            
            # STAGE 2: FLORENCE-2 VISION MODEL FOR NON-EXTRACTABLE STRUCTURES
            # Parses visual layout, diagrams, flowcharts, tables, and visual element graphs
            try:
                vision_pipeline = VisionPipeline(mock_vlm=False)
                v_blocks, v_rels = vision_pipeline.process_visual_asset(
                    image=processed_image, 
                    parent_document_id=document_id, 
                    parent_page_id=page_ko_id, 
                    page_number=1
                )
                blocks.extend(v_blocks)
                relationships.extend(v_rels)
                logger.info(f"VisionPipeline produced {len(v_blocks)} visual blocks for {cdo.filename}.")
            except Exception as ve:
                logger.warning(f"VisionPipeline analysis failed for {cdo.filename}: {ve}")
            
            quality_metrics = {
                "initial_iqs": quality_report.quality_score,
                "final_iqs": quality_report.quality_score,
                "category": classification["final_category"]
            }
            if overall_confidence <= 0.0:
                overall_confidence = 0.95
            
        elif cdo.pages:
            # Phase 2 PDF Adapter logic
            for page in cdo.pages:
                page_num = page["page_num"]
                
                # Create a Page Object for graph
                page_ko_id = str(uuid.uuid4())
                blocks.append(KnowledgeObject(
                    knowledge_object_id=page_ko_id,
                    parent_document_id=document_id,
                    block_type="page",
                    content=f"Page {page_num + 1} of {cdo.filename}",
                    engine_used="native_pdf",
                    confidence=1.0,
                    page_number=page_num + 1
                ))
                
                for text_block in page.get("text_blocks", []):
                    ko_id = str(uuid.uuid4())
                    blocks.append(KnowledgeObject(
                        knowledge_object_id=ko_id,
                        parent_document_id=document_id,
                        parent_object_id=page_ko_id,
                        page_number=page_num + 1,
                        block_type="paragraph",
                        content=text_block,
                        engine_used="native_pdf",
                        confidence=1.0,
                        metadata={"page_num": page_num}
                    ))
                    relationships.append(RelationshipEdge(
                        source_id=ko_id,
                        target_id=page_ko_id,
                        relationship_type="CHILD_OF"
                    ))
                    
                for table in page.get("tables", []):
                    ko_id = str(uuid.uuid4())
                    table_content = table.get("markdown") if isinstance(table, dict) and table.get("markdown") else str(table)
                    table_bbox = table.get("bounding_box") if isinstance(table, dict) else None
                    blocks.append(KnowledgeObject(
                        knowledge_object_id=ko_id,
                        parent_document_id=document_id,
                        parent_object_id=page_ko_id,
                        page_number=page_num + 1,
                        block_type="table",
                        content=table_content,
                        engine_used="native_pdf",
                        confidence=1.0,
                        bounding_box=table_bbox,
                        metadata={"page_num": page_num}
                    ))
                    relationships.append(RelationshipEdge(
                        source_id=ko_id,
                        target_id=page_ko_id,
                        relationship_type="CHILD_OF"
                    ))
                    
                # Phase 2 Vision Intelligence for non-extractable visual elements on PDF page
                for img_asset in page.get("images", []):
                    if not hasattr(img_asset, "shape") or img_asset.shape[0] < 60 or img_asset.shape[1] < 60:
                        continue # Skip tiny icons, transparent pixels, bullets
                    try:
                        vision_pipeline = VisionPipeline(mock_vlm=False)
                        v_blocks, v_rels = vision_pipeline.process_visual_asset(
                            image=img_asset,
                            parent_document_id=document_id,
                            parent_page_id=page_ko_id,
                            page_number=page_num + 1
                        )
                        blocks.extend(v_blocks)
                        relationships.extend(v_rels)
                    except Exception as ve:
                        logger.warning(f"PDF page {page_num+1} visual analysis failed: {ve}")

                # Phase 2 Step 4 DOCX Adapter logic (ordered elements)
                if page.get("elements"):
                    active_headings = {0: page_ko_id} # Level -> parent KO ID
                    processed_headers_footers = set()
                    
                    for element in page["elements"]:
                        el_type = element["type"]
                        
                        if el_type == "section_start":
                            continue # We will attach headers/footers directly to document root or track section metadata
                            
                        if el_type in ["header", "footer"]:
                            hf_id = element["id"]
                            if element.get("is_new") and hf_id not in processed_headers_footers:
                                processed_headers_footers.add(hf_id)
                                
                                # Create Header/Footer block
                                blocks.append(KnowledgeObject(
                                    knowledge_object_id=hf_id,
                                    parent_document_id=document_id,
                                    parent_object_id=page_ko_id,
                                    page_number=page_num + 1,
                                    block_type=el_type.upper(),
                                    content=f"{el_type.capitalize()}",
                                    engine_used="native_docx",
                                    confidence=1.0,
                                    metadata={"object_type": el_type.upper()}
                                ))
                                relationships.append(RelationshipEdge(
                                    source_id=hf_id,
                                    target_id=page_ko_id,
                                    relationship_type="CHILD_OF"
                                ))
                                
                                # Process children of Header/Footer
                                for child_el in element.get("elements", []):
                                    child_type = child_el["type"]
                                    c_id = str(uuid.uuid4())
                                    
                                    if child_type in ["paragraph", "heading", "list"]:
                                        blocks.append(KnowledgeObject(
                                            knowledge_object_id=c_id,
                                            parent_document_id=document_id,
                                            parent_object_id=hf_id,
                                            page_number=page_num + 1,
                                            block_type=child_type,
                                            content=child_el.get("text", ""),
                                            engine_used="native_docx",
                                            confidence=1.0,
                                            metadata=child_el.get("formatting", {})
                                        ))
                                        relationships.append(RelationshipEdge(
                                            source_id=c_id,
                                            target_id=hf_id,
                                            relationship_type="CHILD_OF"
                                        ))
                                    elif child_type == "image":
                                        img_bytes = child_el["image_bytes"]
                                        nparr = np.frombuffer(img_bytes, np.uint8)
                                        img_cv = cv2.imdecode(nparr, cv2.IMREAD_COLOR)
                                        
                                        vision_pipeline = VisionPipeline(mock_vlm=False)
                                        v_blocks, v_rels = vision_pipeline.process_visual_asset(
                                            image=img_cv,
                                            parent_document_id=document_id,
                                            parent_page_id=hf_id,
                                            page_number=page_num + 1
                                        )
                                        blocks.extend(v_blocks)
                                        relationships.extend(v_rels)
                                        
                            elif not element.get("is_new"):
                                # Ensure we record the relationship if it's reused, 
                                # but wait, we attached them to the document root anyway.
                                # If we had section objects, we'd add an edge to the new section.
                                pass
                                
                            continue
                            
                        ko_id = str(uuid.uuid4())
                        parent_id = page_ko_id
                        
                        if el_type == "heading":
                            level = element.get("level", 1)
                            # Find nearest parent heading
                            for l in range(level - 1, -1, -1):
                                if l in active_headings:
                                    parent_id = active_headings[l]
                                    break
                            active_headings[level] = ko_id
                            # Clear deeper active headings
                            for l in list(active_headings.keys()):
                                if l > level:
                                    del active_headings[l]
                        elif el_type in ["paragraph", "list"]:
                            # Attach to deepest active heading
                            max_level = max(active_headings.keys()) if active_headings else 0
                            parent_id = active_headings.get(max_level, page_ko_id)
                        
                        if el_type in ["paragraph", "heading", "list"]:
                            blocks.append(KnowledgeObject(
                                knowledge_object_id=ko_id,
                                parent_document_id=document_id,
                                parent_object_id=parent_id,
                                page_number=page_num + 1,
                                block_type=el_type,
                                content=element.get("text", ""),
                                engine_used="native_docx",
                                confidence=1.0,
                                metadata=element.get("formatting", {})
                            ))
                            relationships.append(RelationshipEdge(
                                source_id=ko_id,
                                target_id=parent_id,
                                relationship_type="CHILD_OF"
                            ))
                            
                        elif el_type == "table":
                            # Attach table to deepest heading or page
                            max_level = max(active_headings.keys()) if active_headings else 0
                            parent_id = active_headings.get(max_level, page_ko_id)
                            
                            blocks.append(KnowledgeObject(
                                knowledge_object_id=ko_id,
                                parent_document_id=document_id,
                                parent_object_id=parent_id,
                                page_number=page_num + 1,
                                block_type="table",
                                content=f"Table with {element.get('num_rows')} rows and {element.get('num_cols')} cols",
                                engine_used=f"native_{cdo.modality}",
                                confidence=1.0,
                                metadata={"bounding_box": element.get("bounding_box")} if element.get("bounding_box") else {}
                            ))
                            relationships.append(RelationshipEdge(
                                source_id=ko_id,
                                target_id=parent_id,
                                relationship_type="CHILD_OF"
                            ))
                            
                            # Parse Rows and Cells
                            for row in element.get("rows", []):
                                row_ko_id = str(uuid.uuid4())
                                blocks.append(KnowledgeObject(
                                    knowledge_object_id=row_ko_id,
                                    parent_document_id=document_id,
                                    parent_object_id=ko_id,
                                    page_number=page_num + 1,
                                    block_type="row",
                                    content=f"Row {row.get('row_index')}",
                                    engine_used=f"native_{cdo.modality}",
                                    confidence=1.0
                                ))
                                relationships.append(RelationshipEdge(
                                    source_id=row_ko_id,
                                    target_id=ko_id,
                                    relationship_type="CHILD_OF"
                                ))
                                for cell in row.get("cells", []):
                                    cell_ko_id = str(uuid.uuid4())
                                    cell_meta = {"row_index": cell.get("row_index"), "col_index": cell.get("col_index")}
                                    for mk in ["column_name", "cell_coordinate", "sheet_name", "data_type", "modality"]:
                                        if mk in cell:
                                            cell_meta[mk] = cell[mk]
                                            
                                    blocks.append(KnowledgeObject(
                                        knowledge_object_id=cell_ko_id,
                                        parent_document_id=document_id,
                                        parent_object_id=row_ko_id,
                                        page_number=page_num + 1,
                                        block_type="cell",
                                        content=cell.get("text", ""),
                                        engine_used=f"native_{cdo.modality}",
                                        confidence=1.0,
                                        metadata=cell_meta
                                    ))
                                    relationships.append(RelationshipEdge(
                                        source_id=cell_ko_id,
                                        target_id=row_ko_id,
                                        relationship_type="CHILD_OF"
                                    ))
                                    
                        elif el_type in ["title", "text_box", "speaker_notes"]:
                            # PPTX Text Elements
                            parent_id = page_ko_id
                            block_type = "heading" if el_type == "title" else "paragraph"
                            meta = element.get("formatting", {})
                            if element.get("bounding_box"):
                                meta["bounding_box"] = element["bounding_box"]
                            if el_type == "speaker_notes":
                                meta["is_speaker_notes"] = True
                                
                            blocks.append(KnowledgeObject(
                                knowledge_object_id=ko_id,
                                parent_document_id=document_id,
                                parent_object_id=parent_id,
                                page_number=page_num + 1,
                                block_type=block_type,
                                content=element.get("text", ""),
                                engine_used="native_pptx",
                                confidence=1.0,
                                metadata=meta
                            ))
                            relationships.append(RelationshipEdge(
                                source_id=ko_id,
                                target_id=parent_id,
                                relationship_type="CHILD_OF"
                            ))
                            
                        elif el_type == "chart":
                            # PPTX Chart
                            parent_id = page_ko_id
                            blocks.append(KnowledgeObject(
                                knowledge_object_id=ko_id,
                                parent_document_id=document_id,
                                parent_object_id=parent_id,
                                page_number=page_num + 1,
                                block_type="chart",
                                content=element.get("chart_title", "Chart"),
                                engine_used="native_pptx",
                                confidence=1.0,
                                metadata={
                                    "chart_type": element.get("chart_type"),
                                    "bounding_box": element.get("bounding_box")
                                }
                            ))
                            relationships.append(RelationshipEdge(
                                source_id=ko_id,
                                target_id=parent_id,
                                relationship_type="CHILD_OF"
                            ))
                            
                            for series in element.get("series", []):
                                series_ko_id = str(uuid.uuid4())
                                blocks.append(KnowledgeObject(
                                    knowledge_object_id=series_ko_id,
                                    parent_document_id=document_id,
                                    parent_object_id=ko_id,
                                    page_number=page_num + 1,
                                    block_type="dataseries",
                                    content=f"Series: {series.get('name', 'Unknown')}, Values: {series.get('values', [])}",
                                    engine_used="native_pptx",
                                    confidence=1.0
                                ))
                                relationships.append(RelationshipEdge(
                                    source_id=series_ko_id,
                                    target_id=ko_id,
                                    relationship_type="CHILD_OF"
                                ))
                                
                        elif el_type in ["shape", "group"]:
                            # Send to vision pipeline fallback if complex, for now just placeholder
                            parent_id = page_ko_id
                            blocks.append(KnowledgeObject(
                                knowledge_object_id=ko_id,
                                parent_document_id=document_id,
                                parent_object_id=parent_id,
                                page_number=page_num + 1,
                                block_type="shape",
                                content=element.get("text", f"{el_type.capitalize()} Object"),
                                engine_used="native_pptx",
                                confidence=1.0,
                                metadata={"bounding_box": element.get("bounding_box")}
                            ))
                            relationships.append(RelationshipEdge(
                                source_id=ko_id,
                                target_id=parent_id,
                                relationship_type="CHILD_OF"
                            ))
                            
                        elif el_type == "image":
                            # Route image to Vision Pipeline
                            img_bytes = element["image_bytes"]
                            nparr = np.frombuffer(img_bytes, np.uint8)
                            img_cv = cv2.imdecode(nparr, cv2.IMREAD_COLOR)
                            
                            max_level = max(active_headings.keys()) if active_headings else 0
                            parent_id = active_headings.get(max_level, page_ko_id)
                            
                            vision_pipeline = VisionPipeline(mock_vlm=False)
                            v_blocks, v_rels = vision_pipeline.process_visual_asset(
                                image=img_cv,
                                parent_document_id=document_id,
                                parent_page_id=parent_id,
                                page_number=page_num + 1
                            )
                            blocks.extend(v_blocks)
                            relationships.extend(v_rels)
                            
                        elif el_type == "audio_segment":
                            blocks.append(KnowledgeObject(
                                knowledge_object_id=ko_id,
                                parent_document_id=document_id,
                                parent_object_id=page_ko_id,
                                page_number=page_num + 1,
                                block_type="audio_segment",
                                content=element.get("text", ""),
                                engine_used="whisper_audio",
                                confidence=element.get("confidence", 1.0),
                                metadata={
                                    "start_time": element.get("start_time", 0.0),
                                    "end_time": element.get("end_time", 0.0),
                                    "timestamp_str": element.get("timestamp_str", "00:00 - 00:00"),
                                    "modality": "audio"
                                }
                            ))
                            relationships.append(RelationshipEdge(
                                source_id=ko_id,
                                target_id=page_ko_id,
                                relationship_type="CHILD_OF"
                            ))
                            
            quality_metrics = {"category": cdo.modality}
            
        processing_metadata = ProcessingMetadata(
            profile_used=profile_used,
            enhancement_trace=enhancement_trace,
            quality_metrics=quality_metrics,
            ocr_performance={"confidence": overall_confidence}
        )
        
        # Entity Extraction using AdvancedLocalEntityExtractor with classification markings
        from app.core.nlp.advanced_entity_extractor import AdvancedLocalEntityExtractor
        entity_extractor = AdvancedLocalEntityExtractor()
        new_entities = []
        new_relationships = []
        
        for block in blocks:
            if block.content and block.block_type in ["paragraph", "heading", "text", "cell", "audio_segment", "video_segment"]:
                extracted = entity_extractor.extract_entities(block.content)
                for ent in extracted:
                    ent_id = str(uuid.uuid4())
                    new_entities.append(KnowledgeObject(
                        knowledge_object_id=ent_id,
                        parent_document_id=document_id,
                        parent_object_id=block.knowledge_object_id,
                        page_number=block.page_number,
                        block_type="entity",
                        content=ent["value"],
                        engine_used="advanced_entity_extractor",
                        confidence=1.0,
                        metadata={"entity_type": ent["type"]}
                    ))
                    relationships.append(RelationshipEdge(
                        source_id=block.knowledge_object_id,
                        target_id=ent_id,
                        relationship_type="MENTIONS"
                    ))
        
        blocks.extend(new_entities)
        relationships.extend(new_relationships)
        
        schema = UniversalKnowledgeSchema(
            document_id=document_id,
            sha256_hash=sha256_hash,
            source_file=cdo.filename,
            metadata=cdo.metadata,
            processing_metadata=processing_metadata,
            semantic_blocks=blocks,
            relationships=relationships
        )
        # Persist Knowledge Objects & Relationship Edges into SQLite Knowledge Graph
        from app.models.database import db_manager
        db_manager.save_knowledge_objects([b.model_dump() if hasattr(b, 'model_dump') else b.dict() for b in blocks])
        db_manager.save_relationship_edges([r.model_dump() if hasattr(r, 'model_dump') else r.dict() for r in relationships])

        # 9. Semantic Chunking
        chunks = SemanticChunker.chunk_schema(schema)
        event_bus.emit("ChunkingCompleted", {"document_id": document_id, "chunk_count": len(chunks)})
        
        # Cache the processed schema
        DocumentFingerprinter.cache_schema(schema)
        
        # Clean up temporary assets from Ingestion
        from app.core.resource_manager import resource_manager
        resource_manager.clear_temp_assets(document_id)
        
        return schema, chunks
