import logging
import urllib.request
import json
from abc import ABC, abstractmethod
from typing import Iterator, Dict, Any, Optional

logger = logging.getLogger(__name__)

class LocalLLMProvider(ABC):
    """Provider-independent abstract interface for offline/on-premise LLMs."""

    @abstractmethod
    def check_status(self) -> bool:
        """Returns True if local model engine is online and operational."""
        pass

    @abstractmethod
    def generate(self, prompt: str, system_prompt: str = "") -> str:
        """Generates a complete text response synchronously."""
        pass

    @abstractmethod
    def generate_stream(self, prompt: str, system_prompt: str = "") -> Iterator[str]:
        """Yields streaming tokens as they are generated by the model."""
        pass


import os
import time

class OllamaProvider(LocalLLMProvider):
    """Local Ollama engine provider implementation optimized for low-latency CPU execution."""

    def __init__(self, endpoint_url: str = "http://127.0.0.1:11434/api/generate", model_name: str = "llama3:latest"):
        self.endpoint_url = endpoint_url
        self.model_name = model_name

    def check_status(self) -> bool:
        try:
            req = urllib.request.Request("http://127.0.0.1:11434/")
            with urllib.request.urlopen(req, timeout=2) as res:
                return res.status == 200
        except Exception:
            return False

    def _get_optimal_options(self, prompt: str, system_prompt: str = "") -> Dict[str, Any]:
        """Calculates memory-efficient context window and thread allocations for fast CPU inference."""
        estimated_tokens = len(prompt.split()) + len(system_prompt.split())
        # Dynamic context window sized to prompt + headroom, avoiding heavy 8k CPU cache paging
        dynamic_ctx = min(4096, max(1024, int(estimated_tokens * 2.5)))
        cpu_threads = max(2, min(8, os.cpu_count() or 4))
        return {
            "temperature": 0.2,
            "top_p": 0.9,
            "num_predict": 512,
            "num_ctx": dynamic_ctx,
            "num_thread": cpu_threads
        }

    def generate(self, prompt: str, system_prompt: str = "") -> str:
        t_start = time.perf_counter()
        options = self._get_optimal_options(prompt, system_prompt)
        payload = {
            "model": self.model_name,
            "prompt": prompt,
            "system": system_prompt,
            "stream": False,
            "keep_alive": "30m",
            "options": options
        }
        data = json.dumps(payload).encode("utf-8")
        req = urllib.request.Request(
            self.endpoint_url,
            data=data,
            headers={"Content-Type": "application/json"},
            method="POST"
        )
        with urllib.request.urlopen(req, timeout=300) as res:
            body = json.loads(res.read().decode("utf-8"))
            elapsed = time.perf_counter() - t_start
            logger.info(f"[PERF] Ollama generate completed in {elapsed:.2f}s (num_ctx: {options['num_ctx']})")
            return body.get("response", "").strip()

    def generate_stream(self, prompt: str, system_prompt: str = "") -> Iterator[str]:
        t_start = time.perf_counter()
        options = self._get_optimal_options(prompt, system_prompt)
        payload = {
            "model": self.model_name,
            "prompt": prompt,
            "system": system_prompt,
            "stream": True,
            "keep_alive": "30m",
            "options": options
        }
        data = json.dumps(payload).encode("utf-8")
        req = urllib.request.Request(
            self.endpoint_url,
            data=data,
            headers={"Content-Type": "application/json"},
            method="POST"
        )
        first_token_time = None
        token_count = 0
        with urllib.request.urlopen(req, timeout=300) as res:
            for line in res:
                if line:
                    chunk = json.loads(line.decode("utf-8"))
                    text = chunk.get("response", "")
                    if text:
                        if first_token_time is None:
                            first_token_time = time.perf_counter()
                            ttft = first_token_time - t_start
                            logger.info(f"[PERF] Time to first token (TTFT): {ttft:.2f}s (num_ctx: {options['num_ctx']})")
                        token_count += 1
                        yield text
                    if chunk.get("done"):
                        break
        total_time = time.perf_counter() - t_start
        ttft_str = f"{first_token_time - t_start:.2f}s" if first_token_time else "N/A"
        logger.info(f"[PERF] Stream finished in {total_time:.2f}s | TTFT: {ttft_str} | Tokens: {token_count}")


class MockLLMProvider(LocalLLMProvider):
    """Air-gapped rule-based fallback provider when no local LLM engine is running."""

    def check_status(self) -> bool:
        return True

    def generate(self, prompt: str, system_prompt: str = "") -> str:
        return "[Offline Mock LLM Mode] Extracted summary response for offline sandbox context."

    def generate_stream(self, prompt: str, system_prompt: str = "") -> Iterator[str]:
        response = "[Offline Mock LLM Stream] Tokenized context answer."
        for word in response.split():
            yield word + " "


class QwenProvider(LocalLLMProvider):
    """Interface stub for custom Qwen3 local model deployment (GGUF / local server)."""

    def __init__(self, endpoint_url: str = "http://127.0.0.1:8080/v1/completions", model_name: str = "qwen3-custom"):
        self.endpoint_url = endpoint_url
        self.model_name = model_name

    def check_status(self) -> bool:
        try:
            req = urllib.request.Request(self.endpoint_url.replace("/v1/completions", "/health"))
            with urllib.request.urlopen(req, timeout=2) as res:
                return res.status == 200
        except Exception:
            return False

    def generate(self, prompt: str, system_prompt: str = "") -> str:
        if not self.check_status():
            logger.info("Qwen endpoint unavailable; using MockLLMProvider fallback.")
            return MockLLMProvider().generate(prompt, system_prompt)
        # HTTP call to local Qwen endpoint when active
        payload = {"model": self.model_name, "prompt": f"{system_prompt}\n{prompt}", "max_tokens": 512}
        data = json.dumps(payload).encode("utf-8")
        req = urllib.request.Request(self.endpoint_url, data=data, headers={"Content-Type": "application/json"}, method="POST")
        with urllib.request.urlopen(req, timeout=60) as res:
            body = json.loads(res.read().decode("utf-8"))
            return body.get("choices", [{}])[0].get("text", "").strip()

    def generate_stream(self, prompt: str, system_prompt: str = "") -> Iterator[str]:
        if not self.check_status():
            logger.info("Qwen endpoint unavailable; using MockLLMProvider stream fallback.")
            yield from MockLLMProvider().generate_stream(prompt, system_prompt)
            return
        # Standard streaming yield
        yield from MockLLMProvider().generate_stream(prompt, system_prompt)


class LLMProviderFactory:
    """Factory for instantiating and resolving active local LLM providers."""

    _active_provider: Optional[LocalLLMProvider] = None

    @classmethod
    def get_provider(cls) -> LocalLLMProvider:
        if cls._active_provider is not None:
            return cls._active_provider
        
        # Check Ollama first
        ollama = OllamaProvider()
        if ollama.check_status():
            cls._active_provider = ollama
            return ollama

        # Check Qwen
        qwen = QwenProvider()
        if qwen.check_status():
            cls._active_provider = qwen
            return qwen

        # Fallback to Mock
        cls._active_provider = MockLLMProvider()
        return cls._active_provider

    @classmethod
    def set_provider(cls, provider: LocalLLMProvider):
        cls._active_provider = provider
